comment out announcements for a second
Something to do with django.contrib.flatpages is causing a "django
can't even"

```
  File "rooibos/ui/urls.py", line 36, in <module>
    'flatpage_content_type':
ContentType.objects.get_for_model(FlatPage).id,
  File "django/contrib/contenttypes/models.py", line 58, in
get_for_model
    " is migrated before trying to migrate apps individually."
RuntimeError: Error creating new content types.
Please make sure contenttypes is migrated before trying to migrate apps
individually.
```