checking to see how things run in Django 1.7
already found one problem - need to finish the rest of the simplejson
eliminations.

```
File "/Users/hanley/Dev/hacking-mdid3/rooibos/storage/multimedia.py",
line 8, in <module>
    from django.utils import simplejson
ImportError: cannot import name simplejson
```